### ISSUE TITLE
Bridge Plugin 404

### ISSUE THREAD

**Issue by ghost** [hugohuang1111/sdkbox-plugin-appsflyer#1]
* SDKBox tools [sbc in GitHub](https://raw.githubusercontent.com/sdkbox/storage/master/sbc/sbc) 

* SDKBox Bridge Plugin [Bridge.zip in GitHub](https://raw.githubusercontent.com/sdkbox/storage/master/plugins/Bridge.zip) 

The two repos do not exists, please check it.

**Comment by hugohuang1111** [comment]
em, fixed, move it Google Drive. pls check.
